---
title: "thresh_vignette"
author: "Bruce Martin"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
set.seed(123)
library(phytools)
library(abind)
library(contSimmap)
tree<-pbtree(n=20)
x_complete<-fastBM(tree,internal=T)
x<-x_complete[1:length(tree$tip.label)]
sim<-simBM(tree,x,n.sim=100)
threshed<-thresh(tree,sim,0.5)
x_disc<-ifelse(x>0.5,1,0)
true_hist<-ifelse(x_complete>0.5,1,0)
simmapSYM<-make.simmap(tree,x_disc,nsim=100)
simmapARD<-make.simmap(tree,x_disc,model='ARD',nsim=100)

plot(describe.simmap(threshed))
coords<-get.node.coords()
points(coords,bg=c('black','red')[true_hist+1],col='white',pch=21)
invisible(sapply(threshed,markChanges,colors=setNames(alter.cols(c('black','red'),0.2),c('0','1'))))

plot(describe.simmap(simmapSYM))
points(coords,bg=c('black','red')[true_hist+1],col='white',pch=21)
invisible(sapply(simmapSYM,markChanges,colors=setNames(alter.cols(c('black','red'),0.2),c('0','1'))))

plot(describe.simmap(simmapARD))
points(coords,bg=c('black','red')[true_hist+1],col='white',pch=21)
invisible(sapply(simmapARD,markChanges,colors=setNames(alter.cols(c('black','red'),0.2),c('0','1'))))
```