// Generated by rstantools.  Do not edit by hand.

/*
    contSimmap is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    contSimmap is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with contSimmap.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_univar_evorates_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_univar_evorates");
    reader.add_event(281, 279, "end", "model_univar_evorates");
    return reader;
}
template <typename T1__, typename T2__, typename T3__>
Eigen::Matrix<typename boost::math::tools::promote_args<T1__, T2__, T3__>::type, Eigen::Dynamic, 1>
get_SE(const int& n,
           const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& p_SE,
           const Eigen::Matrix<T2__, Eigen::Dynamic, 1>& inv_n_obs,
           const std::vector<T3__>& Ysig2,
           const std::vector<int>& which_mis_SE,
           const int& has_mis_SE, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 4;
        validate_non_negative_index("SE", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> SE(n);
        stan::math::initialize(SE, DUMMY_VAR__);
        stan::math::fill(SE, DUMMY_VAR__);
        current_statement_begin__ = 5;
        stan::math::assign(SE, p_SE);
        current_statement_begin__ = 6;
        if (as_bool(has_mis_SE)) {
            current_statement_begin__ = 7;
            stan::model::assign(SE, 
                        stan::model::cons_list(stan::model::index_multi(which_mis_SE), stan::model::nil_index_list()), 
                        multiply(stan::model::rvalue(inv_n_obs, stan::model::cons_list(stan::model::index_multi(which_mis_SE), stan::model::nil_index_list()), "inv_n_obs"), get_base1(Ysig2, 1, "Ysig2", 1)), 
                        "assigning variable SE");
        }
        current_statement_begin__ = 9;
        return stan::math::promote_scalar<fun_return_scalar_t__>(SE);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct get_SE_functor__ {
    template <typename T1__, typename T2__, typename T3__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T1__, T2__, T3__>::type, Eigen::Dynamic, 1>
    operator()(const int& n,
           const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& p_SE,
           const Eigen::Matrix<T2__, Eigen::Dynamic, 1>& inv_n_obs,
           const std::vector<T3__>& Ysig2,
           const std::vector<int>& which_mis_SE,
           const int& has_mis_SE, std::ostream* pstream__) const {
        return get_SE(n, p_SE, inv_n_obs, Ysig2, which_mis_SE, has_mis_SE, pstream__);
    }
};
template <typename T1__, typename T8__, typename T9__, typename T10__>
typename boost::math::tools::promote_args<T1__, T8__, T9__, T10__>::type
prune(const int& n,
          const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& prune_T,
          const std::vector<std::vector<int> >& des_e,
          const std::vector<int>& tip_e,
          const std::vector<int>& real_e,
          const std::vector<int>& postorder,
          const std::vector<int>& mis_code,
          const std::vector<int>& which_non_mis,
          const Eigen::Matrix<T8__, Eigen::Dynamic, 1>& X,
          const Eigen::Matrix<T9__, Eigen::Dynamic, 1>& SE,
          const Eigen::Matrix<T10__, Eigen::Dynamic, 1>& R, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T1__, T8__, T9__, T10__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 15;
        validate_non_negative_index("SS", "((2 * n) - 1)", ((2 * n) - 1));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> SS(((2 * n) - 1));
        stan::math::initialize(SS, DUMMY_VAR__);
        stan::math::fill(SS, DUMMY_VAR__);
        current_statement_begin__ = 16;
        validate_non_negative_index("XX", "((2 * n) - 1)", ((2 * n) - 1));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> XX(((2 * n) - 1));
        stan::math::initialize(XX, DUMMY_VAR__);
        stan::math::fill(XX, DUMMY_VAR__);
        current_statement_begin__ = 17;
        validate_non_negative_index("VV", "((2 * n) - 1)", ((2 * n) - 1));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> VV(((2 * n) - 1));
        stan::math::initialize(VV, DUMMY_VAR__);
        stan::math::fill(VV, DUMMY_VAR__);
        current_statement_begin__ = 18;
        validate_non_negative_index("LL", "(n - 1)", (n - 1));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> LL((n - 1));
        stan::math::initialize(LL, DUMMY_VAR__);
        stan::math::fill(LL, DUMMY_VAR__);
        current_statement_begin__ = 19;
        int counter(0);
        (void) counter;  // dummy to suppress unused var warning
        stan::math::fill(counter, std::numeric_limits<int>::min());
        current_statement_begin__ = 20;
        int counter_non_mis(0);
        (void) counter_non_mis;  // dummy to suppress unused var warning
        stan::math::fill(counter_non_mis, std::numeric_limits<int>::min());
        current_statement_begin__ = 21;
        validate_non_negative_index("des_X", "2", 2);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> des_X(2);
        stan::math::initialize(des_X, DUMMY_VAR__);
        stan::math::fill(des_X, DUMMY_VAR__);
        current_statement_begin__ = 22;
        validate_non_negative_index("des_V", "2", 2);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> des_V(2);
        stan::math::initialize(des_V, DUMMY_VAR__);
        stan::math::fill(des_V, DUMMY_VAR__);
        current_statement_begin__ = 23;
        local_scalar_t__ sum_des_V(DUMMY_VAR__);
        (void) sum_des_V;  // dummy to suppress unused var warning
        stan::math::initialize(sum_des_V, DUMMY_VAR__);
        stan::math::fill(sum_des_V, DUMMY_VAR__);
        current_statement_begin__ = 24;
        stan::math::assign(SS, rep_vector(0, ((2 * n) - 1)));
        current_statement_begin__ = 25;
        stan::model::assign(SS, 
                    stan::model::cons_list(stan::model::index_multi(real_e), stan::model::nil_index_list()), 
                    elt_multiply(stan::model::rvalue(prune_T, stan::model::cons_list(stan::model::index_multi(real_e), stan::model::nil_index_list()), "prune_T"), stan::math::exp(R)), 
                    "assigning variable SS");
        current_statement_begin__ = 26;
        stan::model::assign(XX, 
                    stan::model::cons_list(stan::model::index_multi(tip_e), stan::model::nil_index_list()), 
                    X, 
                    "assigning variable XX");
        current_statement_begin__ = 27;
        stan::model::assign(VV, 
                    stan::model::cons_list(stan::model::index_multi(tip_e), stan::model::nil_index_list()), 
                    SE, 
                    "assigning variable VV");
        current_statement_begin__ = 28;
        stan::math::assign(counter, 0);
        current_statement_begin__ = 29;
        stan::math::assign(counter_non_mis, 0);
        current_statement_begin__ = 30;
        for (auto& i : postorder) {
            (void) i;  // dummy to suppress unused var warning
            current_statement_begin__ = 31;
            stan::math::assign(des_X, stan::model::rvalue(XX, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(des_e, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "des_e")), stan::model::nil_index_list()), "XX"));
            current_statement_begin__ = 32;
            stan::math::assign(des_V, add(stan::model::rvalue(VV, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(des_e, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "des_e")), stan::model::nil_index_list()), "VV"), stan::model::rvalue(SS, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(des_e, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "des_e")), stan::model::nil_index_list()), "SS")));
            current_statement_begin__ = 33;
            stan::math::assign(counter, (counter + 1));
            current_statement_begin__ = 34;
            if (as_bool(logical_eq(get_base1(mis_code, counter, "mis_code", 1), 2))) {
                current_statement_begin__ = 35;
                stan::math::assign(sum_des_V, sum(des_V));
                current_statement_begin__ = 36;
                stan::model::assign(LL, 
                            stan::model::cons_list(stan::model::index_uni(counter), stan::model::nil_index_list()), 
                            (stan::math::log(sum_des_V) + (pow((get_base1(des_X, 1, "des_X", 1) - get_base1(des_X, 2, "des_X", 1)), 2) / sum_des_V)), 
                            "assigning variable LL");
                current_statement_begin__ = 37;
                stan::model::assign(XX, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (((get_base1(des_V, 2, "des_V", 1) / sum_des_V) * get_base1(des_X, 1, "des_X", 1)) + ((get_base1(des_V, 1, "des_V", 1) / sum_des_V) * get_base1(des_X, 2, "des_X", 1))), 
                            "assigning variable XX");
                current_statement_begin__ = 39;
                if (as_bool((primitive_value(logical_eq(get_base1(des_V, 1, "des_V", 1), 0)) || primitive_value(logical_eq(get_base1(des_V, 2, "des_V", 1), 0))))) {
                    current_statement_begin__ = 40;
                    stan::model::assign(VV, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                0, 
                                "assigning variable VV");
                } else {
                    current_statement_begin__ = 42;
                    stan::model::assign(VV, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (1 / ((1 / get_base1(des_V, 1, "des_V", 1)) + (1 / get_base1(des_V, 2, "des_V", 1)))), 
                                "assigning variable VV");
                }
            } else if (as_bool(logical_eq(get_base1(mis_code, counter, "mis_code", 1), 1))) {
                current_statement_begin__ = 45;
                stan::model::assign(LL, 
                            stan::model::cons_list(stan::model::index_uni(counter), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable LL");
                current_statement_begin__ = 46;
                stan::math::assign(counter_non_mis, (counter_non_mis + 1));
                current_statement_begin__ = 47;
                stan::model::assign(XX, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            get_base1(des_X, get_base1(which_non_mis, counter_non_mis, "which_non_mis", 1), "des_X", 1), 
                            "assigning variable XX");
                current_statement_begin__ = 48;
                stan::model::assign(VV, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            get_base1(des_V, get_base1(which_non_mis, counter_non_mis, "which_non_mis", 1), "des_V", 1), 
                            "assigning variable VV");
            } else if (as_bool(logical_eq(get_base1(mis_code, counter, "mis_code", 1), 0))) {
                current_statement_begin__ = 50;
                stan::model::assign(LL, 
                            stan::model::cons_list(stan::model::index_uni(counter), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable LL");
                current_statement_begin__ = 51;
                stan::model::assign(XX, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable XX");
                current_statement_begin__ = 52;
                stan::model::assign(VV, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            -(2), 
                            "assigning variable VV");
            }
        }
        current_statement_begin__ = 55;
        return stan::math::promote_scalar<fun_return_scalar_t__>((-(0.5) * sum(LL)));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct prune_functor__ {
    template <typename T1__, typename T8__, typename T9__, typename T10__>
        typename boost::math::tools::promote_args<T1__, T8__, T9__, T10__>::type
    operator()(const int& n,
          const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& prune_T,
          const std::vector<std::vector<int> >& des_e,
          const std::vector<int>& tip_e,
          const std::vector<int>& real_e,
          const std::vector<int>& postorder,
          const std::vector<int>& mis_code,
          const std::vector<int>& which_non_mis,
          const Eigen::Matrix<T8__, Eigen::Dynamic, 1>& X,
          const Eigen::Matrix<T9__, Eigen::Dynamic, 1>& SE,
          const Eigen::Matrix<T10__, Eigen::Dynamic, 1>& R, std::ostream* pstream__) const {
        return prune(n, prune_T, des_e, tip_e, real_e, postorder, mis_code, which_non_mis, X, SE, R, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_univar_evorates
  : public stan::model::model_base_crtp<model_univar_evorates> {
private:
        int n;
        int e;
        matrix_d eV;
        vector_d prune_T;
        std::vector<std::vector<int> > des_e;
        std::vector<int> tip_e;
        std::vector<int> real_e;
        std::vector<int> postorder;
        std::vector<int> mis_code;
        int n_mis_2;
        int n_mis_1;
        std::vector<int> which_non_mis;
        vector_d X;
        vector_d p_SE;
        vector_d inv_n_obs;
        int n_contra;
        vector_d contra;
        vector_d contra_var;
        int n_mis_SE;
        std::vector<int> which_mis_SE;
        double R0_prior_mu;
        double R0_prior_sig;
        double Ysig2_prior_sig;
        double Rsig2_prior_sig;
        double Rmu_prior_mu;
        double Rmu_prior_sig;
        int constr_Rsig2;
        int constr_Rmu;
        double lik_power;
        int has_mis_SE;
        int has_contra;
        double sum_sq_scale_contra;
        matrix_d chol_eV;
        vector_d T_l;
        vector_d T_1;
        vector_d T_2;
        int lik_pow_ind;
        double lik_const;
public:
    model_univar_evorates(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_univar_evorates(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_univar_evorates_namespace::model_univar_evorates";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 61;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            current_statement_begin__ = 62;
            context__.validate_dims("data initialization", "e", "int", context__.to_vec());
            e = int(0);
            vals_i__ = context__.vals_i("e");
            pos__ = 0;
            e = vals_i__[pos__++];
            current_statement_begin__ = 63;
            validate_non_negative_index("eV", "e", e);
            validate_non_negative_index("eV", "e", e);
            context__.validate_dims("data initialization", "eV", "matrix_d", context__.to_vec(e,e));
            eV = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(e, e);
            vals_r__ = context__.vals_r("eV");
            pos__ = 0;
            size_t eV_j_2_max__ = e;
            size_t eV_j_1_max__ = e;
            for (size_t j_2__ = 0; j_2__ < eV_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < eV_j_1_max__; ++j_1__) {
                    eV(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 64;
            validate_non_negative_index("prune_T", "((2 * n) - 1)", ((2 * n) - 1));
            context__.validate_dims("data initialization", "prune_T", "vector_d", context__.to_vec(((2 * n) - 1)));
            prune_T = Eigen::Matrix<double, Eigen::Dynamic, 1>(((2 * n) - 1));
            vals_r__ = context__.vals_r("prune_T");
            pos__ = 0;
            size_t prune_T_j_1_max__ = ((2 * n) - 1);
            for (size_t j_1__ = 0; j_1__ < prune_T_j_1_max__; ++j_1__) {
                prune_T(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 65;
            validate_non_negative_index("des_e", "((2 * n) - 1)", ((2 * n) - 1));
            validate_non_negative_index("des_e", "2", 2);
            context__.validate_dims("data initialization", "des_e", "int", context__.to_vec(((2 * n) - 1),2));
            des_e = std::vector<std::vector<int> >(((2 * n) - 1), std::vector<int>(2, int(0)));
            vals_i__ = context__.vals_i("des_e");
            pos__ = 0;
            size_t des_e_k_0_max__ = ((2 * n) - 1);
            size_t des_e_k_1_max__ = 2;
            for (size_t k_1__ = 0; k_1__ < des_e_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < des_e_k_0_max__; ++k_0__) {
                    des_e[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 66;
            validate_non_negative_index("tip_e", "n", n);
            context__.validate_dims("data initialization", "tip_e", "int", context__.to_vec(n));
            tip_e = std::vector<int>(n, int(0));
            vals_i__ = context__.vals_i("tip_e");
            pos__ = 0;
            size_t tip_e_k_0_max__ = n;
            for (size_t k_0__ = 0; k_0__ < tip_e_k_0_max__; ++k_0__) {
                tip_e[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 67;
            validate_non_negative_index("real_e", "e", e);
            context__.validate_dims("data initialization", "real_e", "int", context__.to_vec(e));
            real_e = std::vector<int>(e, int(0));
            vals_i__ = context__.vals_i("real_e");
            pos__ = 0;
            size_t real_e_k_0_max__ = e;
            for (size_t k_0__ = 0; k_0__ < real_e_k_0_max__; ++k_0__) {
                real_e[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 68;
            validate_non_negative_index("postorder", "(n - 1)", (n - 1));
            context__.validate_dims("data initialization", "postorder", "int", context__.to_vec((n - 1)));
            postorder = std::vector<int>((n - 1), int(0));
            vals_i__ = context__.vals_i("postorder");
            pos__ = 0;
            size_t postorder_k_0_max__ = (n - 1);
            for (size_t k_0__ = 0; k_0__ < postorder_k_0_max__; ++k_0__) {
                postorder[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 77;
            validate_non_negative_index("mis_code", "(n - 1)", (n - 1));
            context__.validate_dims("data initialization", "mis_code", "int", context__.to_vec((n - 1)));
            mis_code = std::vector<int>((n - 1), int(0));
            vals_i__ = context__.vals_i("mis_code");
            pos__ = 0;
            size_t mis_code_k_0_max__ = (n - 1);
            for (size_t k_0__ = 0; k_0__ < mis_code_k_0_max__; ++k_0__) {
                mis_code[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 78;
            context__.validate_dims("data initialization", "n_mis_2", "int", context__.to_vec());
            n_mis_2 = int(0);
            vals_i__ = context__.vals_i("n_mis_2");
            pos__ = 0;
            n_mis_2 = vals_i__[pos__++];
            current_statement_begin__ = 79;
            context__.validate_dims("data initialization", "n_mis_1", "int", context__.to_vec());
            n_mis_1 = int(0);
            vals_i__ = context__.vals_i("n_mis_1");
            pos__ = 0;
            n_mis_1 = vals_i__[pos__++];
            current_statement_begin__ = 80;
            validate_non_negative_index("which_non_mis", "n_mis_1", n_mis_1);
            context__.validate_dims("data initialization", "which_non_mis", "int", context__.to_vec(n_mis_1));
            which_non_mis = std::vector<int>(n_mis_1, int(0));
            vals_i__ = context__.vals_i("which_non_mis");
            pos__ = 0;
            size_t which_non_mis_k_0_max__ = n_mis_1;
            for (size_t k_0__ = 0; k_0__ < which_non_mis_k_0_max__; ++k_0__) {
                which_non_mis[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 84;
            validate_non_negative_index("X", "n", n);
            context__.validate_dims("data initialization", "X", "vector_d", context__.to_vec(n));
            X = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("X");
            pos__ = 0;
            size_t X_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < X_j_1_max__; ++j_1__) {
                X(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 85;
            validate_non_negative_index("p_SE", "n", n);
            context__.validate_dims("data initialization", "p_SE", "vector_d", context__.to_vec(n));
            p_SE = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("p_SE");
            pos__ = 0;
            size_t p_SE_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < p_SE_j_1_max__; ++j_1__) {
                p_SE(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 86;
            validate_non_negative_index("inv_n_obs", "n", n);
            context__.validate_dims("data initialization", "inv_n_obs", "vector_d", context__.to_vec(n));
            inv_n_obs = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("inv_n_obs");
            pos__ = 0;
            size_t inv_n_obs_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < inv_n_obs_j_1_max__; ++j_1__) {
                inv_n_obs(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 87;
            context__.validate_dims("data initialization", "n_contra", "int", context__.to_vec());
            n_contra = int(0);
            vals_i__ = context__.vals_i("n_contra");
            pos__ = 0;
            n_contra = vals_i__[pos__++];
            current_statement_begin__ = 88;
            validate_non_negative_index("contra", "n_contra", n_contra);
            context__.validate_dims("data initialization", "contra", "vector_d", context__.to_vec(n_contra));
            contra = Eigen::Matrix<double, Eigen::Dynamic, 1>(n_contra);
            vals_r__ = context__.vals_r("contra");
            pos__ = 0;
            size_t contra_j_1_max__ = n_contra;
            for (size_t j_1__ = 0; j_1__ < contra_j_1_max__; ++j_1__) {
                contra(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 89;
            validate_non_negative_index("contra_var", "n_contra", n_contra);
            context__.validate_dims("data initialization", "contra_var", "vector_d", context__.to_vec(n_contra));
            contra_var = Eigen::Matrix<double, Eigen::Dynamic, 1>(n_contra);
            vals_r__ = context__.vals_r("contra_var");
            pos__ = 0;
            size_t contra_var_j_1_max__ = n_contra;
            for (size_t j_1__ = 0; j_1__ < contra_var_j_1_max__; ++j_1__) {
                contra_var(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 106;
            context__.validate_dims("data initialization", "n_mis_SE", "int", context__.to_vec());
            n_mis_SE = int(0);
            vals_i__ = context__.vals_i("n_mis_SE");
            pos__ = 0;
            n_mis_SE = vals_i__[pos__++];
            current_statement_begin__ = 107;
            validate_non_negative_index("which_mis_SE", "n_mis_SE", n_mis_SE);
            context__.validate_dims("data initialization", "which_mis_SE", "int", context__.to_vec(n_mis_SE));
            which_mis_SE = std::vector<int>(n_mis_SE, int(0));
            vals_i__ = context__.vals_i("which_mis_SE");
            pos__ = 0;
            size_t which_mis_SE_k_0_max__ = n_mis_SE;
            for (size_t k_0__ = 0; k_0__ < which_mis_SE_k_0_max__; ++k_0__) {
                which_mis_SE[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 111;
            context__.validate_dims("data initialization", "R0_prior_mu", "double", context__.to_vec());
            R0_prior_mu = double(0);
            vals_r__ = context__.vals_r("R0_prior_mu");
            pos__ = 0;
            R0_prior_mu = vals_r__[pos__++];
            current_statement_begin__ = 112;
            context__.validate_dims("data initialization", "R0_prior_sig", "double", context__.to_vec());
            R0_prior_sig = double(0);
            vals_r__ = context__.vals_r("R0_prior_sig");
            pos__ = 0;
            R0_prior_sig = vals_r__[pos__++];
            current_statement_begin__ = 113;
            context__.validate_dims("data initialization", "Ysig2_prior_sig", "double", context__.to_vec());
            Ysig2_prior_sig = double(0);
            vals_r__ = context__.vals_r("Ysig2_prior_sig");
            pos__ = 0;
            Ysig2_prior_sig = vals_r__[pos__++];
            current_statement_begin__ = 114;
            context__.validate_dims("data initialization", "Rsig2_prior_sig", "double", context__.to_vec());
            Rsig2_prior_sig = double(0);
            vals_r__ = context__.vals_r("Rsig2_prior_sig");
            pos__ = 0;
            Rsig2_prior_sig = vals_r__[pos__++];
            current_statement_begin__ = 115;
            context__.validate_dims("data initialization", "Rmu_prior_mu", "double", context__.to_vec());
            Rmu_prior_mu = double(0);
            vals_r__ = context__.vals_r("Rmu_prior_mu");
            pos__ = 0;
            Rmu_prior_mu = vals_r__[pos__++];
            current_statement_begin__ = 116;
            context__.validate_dims("data initialization", "Rmu_prior_sig", "double", context__.to_vec());
            Rmu_prior_sig = double(0);
            vals_r__ = context__.vals_r("Rmu_prior_sig");
            pos__ = 0;
            Rmu_prior_sig = vals_r__[pos__++];
            current_statement_begin__ = 120;
            context__.validate_dims("data initialization", "constr_Rsig2", "int", context__.to_vec());
            constr_Rsig2 = int(0);
            vals_i__ = context__.vals_i("constr_Rsig2");
            pos__ = 0;
            constr_Rsig2 = vals_i__[pos__++];
            current_statement_begin__ = 121;
            context__.validate_dims("data initialization", "constr_Rmu", "int", context__.to_vec());
            constr_Rmu = int(0);
            vals_i__ = context__.vals_i("constr_Rmu");
            pos__ = 0;
            constr_Rmu = vals_i__[pos__++];
            current_statement_begin__ = 125;
            context__.validate_dims("data initialization", "lik_power", "double", context__.to_vec());
            lik_power = double(0);
            vals_r__ = context__.vals_r("lik_power");
            pos__ = 0;
            lik_power = vals_r__[pos__++];
            // initialize transformed data variables
            current_statement_begin__ = 129;
            has_mis_SE = int(0);
            stan::math::fill(has_mis_SE, std::numeric_limits<int>::min());
            current_statement_begin__ = 130;
            has_contra = int(0);
            stan::math::fill(has_contra, std::numeric_limits<int>::min());
            current_statement_begin__ = 131;
            sum_sq_scale_contra = double(0);
            stan::math::fill(sum_sq_scale_contra, DUMMY_VAR__);
            current_statement_begin__ = 132;
            validate_non_negative_index("chol_eV", "(constr_Rsig2 ? 0 : e )", (constr_Rsig2 ? 0 : e ));
            validate_non_negative_index("chol_eV", "(constr_Rsig2 ? 0 : e )", (constr_Rsig2 ? 0 : e ));
            chol_eV = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>((constr_Rsig2 ? 0 : e ), (constr_Rsig2 ? 0 : e ));
            stan::math::fill(chol_eV, DUMMY_VAR__);
            current_statement_begin__ = 133;
            validate_non_negative_index("T_l", "(constr_Rmu ? 0 : e )", (constr_Rmu ? 0 : e ));
            T_l = Eigen::Matrix<double, Eigen::Dynamic, 1>((constr_Rmu ? 0 : e ));
            stan::math::fill(T_l, DUMMY_VAR__);
            current_statement_begin__ = 134;
            validate_non_negative_index("T_1", "(constr_Rmu ? 0 : e )", (constr_Rmu ? 0 : e ));
            T_1 = Eigen::Matrix<double, Eigen::Dynamic, 1>((constr_Rmu ? 0 : e ));
            stan::math::fill(T_1, DUMMY_VAR__);
            current_statement_begin__ = 135;
            validate_non_negative_index("T_2", "(constr_Rmu ? 0 : e )", (constr_Rmu ? 0 : e ));
            T_2 = Eigen::Matrix<double, Eigen::Dynamic, 1>((constr_Rmu ? 0 : e ));
            stan::math::fill(T_2, DUMMY_VAR__);
            current_statement_begin__ = 136;
            lik_pow_ind = int(0);
            stan::math::fill(lik_pow_ind, std::numeric_limits<int>::min());
            current_statement_begin__ = 137;
            lik_const = double(0);
            stan::math::fill(lik_const, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 140;
            if (as_bool(logical_eq(n_mis_SE, 0))) {
                current_statement_begin__ = 141;
                stan::math::assign(has_mis_SE, 0);
            } else {
                current_statement_begin__ = 143;
                stan::math::assign(has_mis_SE, 1);
            }
            current_statement_begin__ = 148;
            if (as_bool(logical_eq(n_contra, 0))) {
                current_statement_begin__ = 149;
                stan::math::assign(has_contra, 0);
            } else {
                current_statement_begin__ = 151;
                stan::math::assign(has_contra, 1);
                current_statement_begin__ = 152;
                stan::math::assign(sum_sq_scale_contra, dot_self(elt_divide(contra, stan::math::sqrt(contra_var))));
            }
            current_statement_begin__ = 157;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 158;
                stan::math::assign(chol_eV, cholesky_decompose(eV));
            }
            current_statement_begin__ = 160;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 161;
                stan::math::assign(T_l, stan::model::rvalue(prune_T, stan::model::cons_list(stan::model::index_multi(real_e), stan::model::nil_index_list()), "prune_T"));
                current_statement_begin__ = 162;
                stan::math::assign(T_1, subtract(diagonal(eV), divide(stan::model::rvalue(prune_T, stan::model::cons_list(stan::model::index_multi(real_e), stan::model::nil_index_list()), "prune_T"), 3)));
                current_statement_begin__ = 163;
                stan::math::assign(T_2, add(diagonal(eV), divide(multiply(2, stan::model::rvalue(prune_T, stan::model::cons_list(stan::model::index_multi(real_e), stan::model::nil_index_list()), "prune_T")), 3)));
            }
            current_statement_begin__ = 167;
            if (as_bool(logical_eq(lik_power, 0))) {
                current_statement_begin__ = 168;
                stan::math::assign(lik_pow_ind, 0);
            } else {
                current_statement_begin__ = 170;
                stan::math::assign(lik_pow_ind, 1);
            }
            current_statement_begin__ = 174;
            stan::math::assign(lik_const, ((-(0.5) * n_mis_2) * stan::math::log((2 * stan::math::pi()))));
            current_statement_begin__ = 175;
            if (as_bool(has_contra)) {
                current_statement_begin__ = 176;
                stan::math::assign(lik_const, (lik_const + (-(0.5) * ((n_contra * stan::math::log((2 * stan::math::pi()))) + sum(stan::math::log(contra_var))))));
            }
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 182;
            num_params_r__ += 1;
            current_statement_begin__ = 183;
            validate_non_negative_index("std_Ysig2", "(has_mis_SE ? 1 : 0 )", (has_mis_SE ? 1 : 0 ));
            num_params_r__ += (1 * (has_mis_SE ? 1 : 0 ));
            current_statement_begin__ = 184;
            validate_non_negative_index("std_Rsig2", "(constr_Rsig2 ? 0 : 1 )", (constr_Rsig2 ? 0 : 1 ));
            num_params_r__ += (1 * (constr_Rsig2 ? 0 : 1 ));
            current_statement_begin__ = 185;
            validate_non_negative_index("std_Rmu", "(constr_Rmu ? 0 : 1 )", (constr_Rmu ? 0 : 1 ));
            num_params_r__ += (1 * (constr_Rmu ? 0 : 1 ));
            current_statement_begin__ = 186;
            validate_non_negative_index("raw_R", "(constr_Rsig2 ? 0 : e )", (constr_Rsig2 ? 0 : e ));
            num_params_r__ += (constr_Rsig2 ? 0 : e );
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_univar_evorates() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 182;
        if (!(context__.contains_r("std_R0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable std_R0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("std_R0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "std_R0", "double", context__.to_vec());
        double std_R0(0);
        std_R0 = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain((-(stan::math::pi()) / 2), (stan::math::pi() / 2), std_R0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable std_R0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 183;
        if (!(context__.contains_r("std_Ysig2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable std_Ysig2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("std_Ysig2");
        pos__ = 0U;
        validate_non_negative_index("std_Ysig2", "(has_mis_SE ? 1 : 0 )", (has_mis_SE ? 1 : 0 ));
        context__.validate_dims("parameter initialization", "std_Ysig2", "double", context__.to_vec((has_mis_SE ? 1 : 0 )));
        std::vector<double> std_Ysig2((has_mis_SE ? 1 : 0 ), double(0));
        size_t std_Ysig2_k_0_max__ = (has_mis_SE ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < std_Ysig2_k_0_max__; ++k_0__) {
            std_Ysig2[k_0__] = vals_r__[pos__++];
        }
        size_t std_Ysig2_i_0_max__ = (has_mis_SE ? 1 : 0 );
        for (size_t i_0__ = 0; i_0__ < std_Ysig2_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lub_unconstrain(0, (stan::math::pi() / 2), std_Ysig2[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable std_Ysig2: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 184;
        if (!(context__.contains_r("std_Rsig2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable std_Rsig2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("std_Rsig2");
        pos__ = 0U;
        validate_non_negative_index("std_Rsig2", "(constr_Rsig2 ? 0 : 1 )", (constr_Rsig2 ? 0 : 1 ));
        context__.validate_dims("parameter initialization", "std_Rsig2", "double", context__.to_vec((constr_Rsig2 ? 0 : 1 )));
        std::vector<double> std_Rsig2((constr_Rsig2 ? 0 : 1 ), double(0));
        size_t std_Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rsig2_k_0_max__; ++k_0__) {
            std_Rsig2[k_0__] = vals_r__[pos__++];
        }
        size_t std_Rsig2_i_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t i_0__ = 0; i_0__ < std_Rsig2_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lub_unconstrain(0, (stan::math::pi() / 2), std_Rsig2[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable std_Rsig2: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 185;
        if (!(context__.contains_r("std_Rmu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable std_Rmu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("std_Rmu");
        pos__ = 0U;
        validate_non_negative_index("std_Rmu", "(constr_Rmu ? 0 : 1 )", (constr_Rmu ? 0 : 1 ));
        context__.validate_dims("parameter initialization", "std_Rmu", "double", context__.to_vec((constr_Rmu ? 0 : 1 )));
        std::vector<double> std_Rmu((constr_Rmu ? 0 : 1 ), double(0));
        size_t std_Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rmu_k_0_max__; ++k_0__) {
            std_Rmu[k_0__] = vals_r__[pos__++];
        }
        size_t std_Rmu_i_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t i_0__ = 0; i_0__ < std_Rmu_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lub_unconstrain((-(stan::math::pi()) / 2), (stan::math::pi() / 2), std_Rmu[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable std_Rmu: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 186;
        if (!(context__.contains_r("raw_R")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable raw_R missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("raw_R");
        pos__ = 0U;
        validate_non_negative_index("raw_R", "(constr_Rsig2 ? 0 : e )", (constr_Rsig2 ? 0 : e ));
        context__.validate_dims("parameter initialization", "raw_R", "vector_d", context__.to_vec((constr_Rsig2 ? 0 : e )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> raw_R((constr_Rsig2 ? 0 : e ));
        size_t raw_R_j_1_max__ = (constr_Rsig2 ? 0 : e );
        for (size_t j_1__ = 0; j_1__ < raw_R_j_1_max__; ++j_1__) {
            raw_R(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(raw_R);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable raw_R: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 182;
            local_scalar_t__ std_R0;
            (void) std_R0;  // dummy to suppress unused var warning
            if (jacobian__)
                std_R0 = in__.scalar_lub_constrain((-(stan::math::pi()) / 2), (stan::math::pi() / 2), lp__);
            else
                std_R0 = in__.scalar_lub_constrain((-(stan::math::pi()) / 2), (stan::math::pi() / 2));
            current_statement_begin__ = 183;
            std::vector<local_scalar_t__> std_Ysig2;
            size_t std_Ysig2_d_0_max__ = (has_mis_SE ? 1 : 0 );
            std_Ysig2.reserve(std_Ysig2_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < std_Ysig2_d_0_max__; ++d_0__) {
                if (jacobian__)
                    std_Ysig2.push_back(in__.scalar_lub_constrain(0, (stan::math::pi() / 2), lp__));
                else
                    std_Ysig2.push_back(in__.scalar_lub_constrain(0, (stan::math::pi() / 2)));
            }
            current_statement_begin__ = 184;
            std::vector<local_scalar_t__> std_Rsig2;
            size_t std_Rsig2_d_0_max__ = (constr_Rsig2 ? 0 : 1 );
            std_Rsig2.reserve(std_Rsig2_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < std_Rsig2_d_0_max__; ++d_0__) {
                if (jacobian__)
                    std_Rsig2.push_back(in__.scalar_lub_constrain(0, (stan::math::pi() / 2), lp__));
                else
                    std_Rsig2.push_back(in__.scalar_lub_constrain(0, (stan::math::pi() / 2)));
            }
            current_statement_begin__ = 185;
            std::vector<local_scalar_t__> std_Rmu;
            size_t std_Rmu_d_0_max__ = (constr_Rmu ? 0 : 1 );
            std_Rmu.reserve(std_Rmu_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < std_Rmu_d_0_max__; ++d_0__) {
                if (jacobian__)
                    std_Rmu.push_back(in__.scalar_lub_constrain((-(stan::math::pi()) / 2), (stan::math::pi() / 2), lp__));
                else
                    std_Rmu.push_back(in__.scalar_lub_constrain((-(stan::math::pi()) / 2), (stan::math::pi() / 2)));
            }
            current_statement_begin__ = 186;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> raw_R;
            (void) raw_R;  // dummy to suppress unused var warning
            if (jacobian__)
                raw_R = in__.vector_constrain((constr_Rsig2 ? 0 : e ), lp__);
            else
                raw_R = in__.vector_constrain((constr_Rsig2 ? 0 : e ));
            // transformed parameters
            current_statement_begin__ = 190;
            local_scalar_t__ R0;
            (void) R0;  // dummy to suppress unused var warning
            stan::math::initialize(R0, DUMMY_VAR__);
            stan::math::fill(R0, DUMMY_VAR__);
            current_statement_begin__ = 191;
            validate_non_negative_index("Ysig2", "(has_mis_SE ? 1 : 0 )", (has_mis_SE ? 1 : 0 ));
            std::vector<local_scalar_t__> Ysig2((has_mis_SE ? 1 : 0 ), local_scalar_t__(0));
            stan::math::initialize(Ysig2, DUMMY_VAR__);
            stan::math::fill(Ysig2, DUMMY_VAR__);
            current_statement_begin__ = 192;
            validate_non_negative_index("SE", "n", n);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> SE(n);
            stan::math::initialize(SE, DUMMY_VAR__);
            stan::math::fill(SE, DUMMY_VAR__);
            current_statement_begin__ = 193;
            validate_non_negative_index("Rsig2", "(constr_Rsig2 ? 0 : 1 )", (constr_Rsig2 ? 0 : 1 ));
            std::vector<local_scalar_t__> Rsig2((constr_Rsig2 ? 0 : 1 ), local_scalar_t__(0));
            stan::math::initialize(Rsig2, DUMMY_VAR__);
            stan::math::fill(Rsig2, DUMMY_VAR__);
            current_statement_begin__ = 194;
            validate_non_negative_index("Rmu", "(constr_Rmu ? 0 : 1 )", (constr_Rmu ? 0 : 1 ));
            std::vector<local_scalar_t__> Rmu((constr_Rmu ? 0 : 1 ), local_scalar_t__(0));
            stan::math::initialize(Rmu, DUMMY_VAR__);
            stan::math::fill(Rmu, DUMMY_VAR__);
            current_statement_begin__ = 195;
            validate_non_negative_index("R", "e", e);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> R(e);
            stan::math::initialize(R, DUMMY_VAR__);
            stan::math::fill(R, DUMMY_VAR__);
            current_statement_begin__ = 196;
            local_scalar_t__ tmp_lik;
            (void) tmp_lik;  // dummy to suppress unused var warning
            stan::math::initialize(tmp_lik, DUMMY_VAR__);
            stan::math::fill(tmp_lik, DUMMY_VAR__);
            current_statement_begin__ = 197;
            validate_non_negative_index("tmp_mu", "e", e);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> tmp_mu(e);
            stan::math::initialize(tmp_mu, DUMMY_VAR__);
            stan::math::fill(tmp_mu, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 201;
            stan::math::assign(R0, (R0_prior_mu + (R0_prior_sig * stan::math::tan(std_R0))));
            current_statement_begin__ = 202;
            if (as_bool(has_mis_SE)) {
                current_statement_begin__ = 203;
                stan::model::assign(Ysig2, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Ysig2_prior_sig * stan::math::tan(get_base1(std_Ysig2, 1, "std_Ysig2", 1))), 
                            "assigning variable Ysig2");
            }
            current_statement_begin__ = 205;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 206;
                stan::model::assign(Rsig2, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Rsig2_prior_sig * stan::math::tan(get_base1(std_Rsig2, 1, "std_Rsig2", 1))), 
                            "assigning variable Rsig2");
            }
            current_statement_begin__ = 208;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 209;
                stan::model::assign(Rmu, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Rmu_prior_mu + (Rmu_prior_sig * stan::math::tan(get_base1(std_Rmu, 1, "std_Rmu", 1)))), 
                            "assigning variable Rmu");
            }
            current_statement_begin__ = 216;
            stan::math::assign(R, rep_vector(R0, e));
            current_statement_begin__ = 217;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 218;
                stan::math::assign(R, add(subtract(subtract(R, stan::math::log(stan::math::fabs(get_base1(Rmu, 1, "Rmu", 1)))), stan::math::log(T_l)), stan::math::log(stan::math::fabs(subtract(stan::math::exp(multiply(get_base1(Rmu, 1, "Rmu", 1), T_2)), stan::math::exp(multiply(get_base1(Rmu, 1, "Rmu", 1), T_1)))))));
            }
            current_statement_begin__ = 220;
            stan::math::assign(tmp_mu, R);
            current_statement_begin__ = 221;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 222;
                stan::math::assign(R, add(R, multiply(multiply(stan::math::sqrt(get_base1(Rsig2, 1, "Rsig2", 1)), chol_eV), raw_R)));
            }
            current_statement_begin__ = 227;
            stan::math::assign(SE, get_SE(n, p_SE, inv_n_obs, Ysig2, which_mis_SE, has_mis_SE, pstream__));
            current_statement_begin__ = 228;
            if (as_bool(lik_pow_ind)) {
                current_statement_begin__ = 229;
                stan::math::assign(tmp_lik, prune(n, prune_T, des_e, tip_e, real_e, postorder, mis_code, which_non_mis, X, SE, R, pstream__));
                current_statement_begin__ = 232;
                if (as_bool(has_contra)) {
                    current_statement_begin__ = 233;
                    stan::math::assign(tmp_lik, (tmp_lik + (-(0.5) * ((sum_sq_scale_contra / get_base1(Ysig2, 1, "Ysig2", 1)) + (n_contra * stan::math::log(get_base1(Ysig2, 1, "Ysig2", 1)))))));
                }
            } else {
                current_statement_begin__ = 236;
                stan::math::assign(tmp_lik, 0);
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 190;
            if (stan::math::is_uninitialized(R0)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: R0";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable R0: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 191;
            size_t Ysig2_k_0_max__ = (has_mis_SE ? 1 : 0 );
            for (size_t k_0__ = 0; k_0__ < Ysig2_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(Ysig2[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: Ysig2" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Ysig2: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 192;
            size_t SE_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < SE_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(SE(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: SE" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable SE: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 193;
            size_t Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rsig2_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(Rsig2[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: Rsig2" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Rsig2: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            size_t Rsig2_i_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t i_0__ = 0; i_0__ < Rsig2_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Rsig2[i_0__]", Rsig2[i_0__], 0);
            }
            current_statement_begin__ = 194;
            size_t Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rmu_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(Rmu[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: Rmu" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Rmu: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 195;
            size_t R_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(R(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: R" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable R: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 196;
            if (stan::math::is_uninitialized(tmp_lik)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: tmp_lik";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable tmp_lik: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 197;
            size_t tmp_mu_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < tmp_mu_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(tmp_mu(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: tmp_mu" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable tmp_mu: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            current_statement_begin__ = 242;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 243;
                lp_accum__.add(std_normal_log<propto__>(raw_R));
            }
            current_statement_begin__ = 248;
            lp_accum__.add((lik_power * tmp_lik));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("std_R0");
        names__.push_back("std_Ysig2");
        names__.push_back("std_Rsig2");
        names__.push_back("std_Rmu");
        names__.push_back("raw_R");
        names__.push_back("R0");
        names__.push_back("Ysig2");
        names__.push_back("SE");
        names__.push_back("Rsig2");
        names__.push_back("Rmu");
        names__.push_back("R");
        names__.push_back("tmp_lik");
        names__.push_back("tmp_mu");
        names__.push_back("lik");
        names__.push_back("prior");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((has_mis_SE ? 1 : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rsig2 ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rmu ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rsig2 ? 0 : e ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((has_mis_SE ? 1 : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rsig2 ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rmu ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(e);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(e);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_univar_evorates_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double std_R0 = in__.scalar_lub_constrain((-(stan::math::pi()) / 2), (stan::math::pi() / 2));
        vars__.push_back(std_R0);
        std::vector<double> std_Ysig2;
        size_t std_Ysig2_d_0_max__ = (has_mis_SE ? 1 : 0 );
        std_Ysig2.reserve(std_Ysig2_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < std_Ysig2_d_0_max__; ++d_0__) {
            std_Ysig2.push_back(in__.scalar_lub_constrain(0, (stan::math::pi() / 2)));
        }
        size_t std_Ysig2_k_0_max__ = (has_mis_SE ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < std_Ysig2_k_0_max__; ++k_0__) {
            vars__.push_back(std_Ysig2[k_0__]);
        }
        std::vector<double> std_Rsig2;
        size_t std_Rsig2_d_0_max__ = (constr_Rsig2 ? 0 : 1 );
        std_Rsig2.reserve(std_Rsig2_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < std_Rsig2_d_0_max__; ++d_0__) {
            std_Rsig2.push_back(in__.scalar_lub_constrain(0, (stan::math::pi() / 2)));
        }
        size_t std_Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rsig2_k_0_max__; ++k_0__) {
            vars__.push_back(std_Rsig2[k_0__]);
        }
        std::vector<double> std_Rmu;
        size_t std_Rmu_d_0_max__ = (constr_Rmu ? 0 : 1 );
        std_Rmu.reserve(std_Rmu_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < std_Rmu_d_0_max__; ++d_0__) {
            std_Rmu.push_back(in__.scalar_lub_constrain((-(stan::math::pi()) / 2), (stan::math::pi() / 2)));
        }
        size_t std_Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rmu_k_0_max__; ++k_0__) {
            vars__.push_back(std_Rmu[k_0__]);
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> raw_R = in__.vector_constrain((constr_Rsig2 ? 0 : e ));
        size_t raw_R_j_1_max__ = (constr_Rsig2 ? 0 : e );
        for (size_t j_1__ = 0; j_1__ < raw_R_j_1_max__; ++j_1__) {
            vars__.push_back(raw_R(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 190;
            double R0;
            (void) R0;  // dummy to suppress unused var warning
            stan::math::initialize(R0, DUMMY_VAR__);
            stan::math::fill(R0, DUMMY_VAR__);
            current_statement_begin__ = 191;
            validate_non_negative_index("Ysig2", "(has_mis_SE ? 1 : 0 )", (has_mis_SE ? 1 : 0 ));
            std::vector<double> Ysig2((has_mis_SE ? 1 : 0 ), double(0));
            stan::math::initialize(Ysig2, DUMMY_VAR__);
            stan::math::fill(Ysig2, DUMMY_VAR__);
            current_statement_begin__ = 192;
            validate_non_negative_index("SE", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> SE(n);
            stan::math::initialize(SE, DUMMY_VAR__);
            stan::math::fill(SE, DUMMY_VAR__);
            current_statement_begin__ = 193;
            validate_non_negative_index("Rsig2", "(constr_Rsig2 ? 0 : 1 )", (constr_Rsig2 ? 0 : 1 ));
            std::vector<double> Rsig2((constr_Rsig2 ? 0 : 1 ), double(0));
            stan::math::initialize(Rsig2, DUMMY_VAR__);
            stan::math::fill(Rsig2, DUMMY_VAR__);
            current_statement_begin__ = 194;
            validate_non_negative_index("Rmu", "(constr_Rmu ? 0 : 1 )", (constr_Rmu ? 0 : 1 ));
            std::vector<double> Rmu((constr_Rmu ? 0 : 1 ), double(0));
            stan::math::initialize(Rmu, DUMMY_VAR__);
            stan::math::fill(Rmu, DUMMY_VAR__);
            current_statement_begin__ = 195;
            validate_non_negative_index("R", "e", e);
            Eigen::Matrix<double, Eigen::Dynamic, 1> R(e);
            stan::math::initialize(R, DUMMY_VAR__);
            stan::math::fill(R, DUMMY_VAR__);
            current_statement_begin__ = 196;
            double tmp_lik;
            (void) tmp_lik;  // dummy to suppress unused var warning
            stan::math::initialize(tmp_lik, DUMMY_VAR__);
            stan::math::fill(tmp_lik, DUMMY_VAR__);
            current_statement_begin__ = 197;
            validate_non_negative_index("tmp_mu", "e", e);
            Eigen::Matrix<double, Eigen::Dynamic, 1> tmp_mu(e);
            stan::math::initialize(tmp_mu, DUMMY_VAR__);
            stan::math::fill(tmp_mu, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 201;
            stan::math::assign(R0, (R0_prior_mu + (R0_prior_sig * stan::math::tan(std_R0))));
            current_statement_begin__ = 202;
            if (as_bool(has_mis_SE)) {
                current_statement_begin__ = 203;
                stan::model::assign(Ysig2, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Ysig2_prior_sig * stan::math::tan(get_base1(std_Ysig2, 1, "std_Ysig2", 1))), 
                            "assigning variable Ysig2");
            }
            current_statement_begin__ = 205;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 206;
                stan::model::assign(Rsig2, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Rsig2_prior_sig * stan::math::tan(get_base1(std_Rsig2, 1, "std_Rsig2", 1))), 
                            "assigning variable Rsig2");
            }
            current_statement_begin__ = 208;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 209;
                stan::model::assign(Rmu, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Rmu_prior_mu + (Rmu_prior_sig * stan::math::tan(get_base1(std_Rmu, 1, "std_Rmu", 1)))), 
                            "assigning variable Rmu");
            }
            current_statement_begin__ = 216;
            stan::math::assign(R, rep_vector(R0, e));
            current_statement_begin__ = 217;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 218;
                stan::math::assign(R, add(subtract(subtract(R, stan::math::log(stan::math::fabs(get_base1(Rmu, 1, "Rmu", 1)))), stan::math::log(T_l)), stan::math::log(stan::math::fabs(subtract(stan::math::exp(multiply(get_base1(Rmu, 1, "Rmu", 1), T_2)), stan::math::exp(multiply(get_base1(Rmu, 1, "Rmu", 1), T_1)))))));
            }
            current_statement_begin__ = 220;
            stan::math::assign(tmp_mu, R);
            current_statement_begin__ = 221;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 222;
                stan::math::assign(R, add(R, multiply(multiply(stan::math::sqrt(get_base1(Rsig2, 1, "Rsig2", 1)), chol_eV), raw_R)));
            }
            current_statement_begin__ = 227;
            stan::math::assign(SE, get_SE(n, p_SE, inv_n_obs, Ysig2, which_mis_SE, has_mis_SE, pstream__));
            current_statement_begin__ = 228;
            if (as_bool(lik_pow_ind)) {
                current_statement_begin__ = 229;
                stan::math::assign(tmp_lik, prune(n, prune_T, des_e, tip_e, real_e, postorder, mis_code, which_non_mis, X, SE, R, pstream__));
                current_statement_begin__ = 232;
                if (as_bool(has_contra)) {
                    current_statement_begin__ = 233;
                    stan::math::assign(tmp_lik, (tmp_lik + (-(0.5) * ((sum_sq_scale_contra / get_base1(Ysig2, 1, "Ysig2", 1)) + (n_contra * stan::math::log(get_base1(Ysig2, 1, "Ysig2", 1)))))));
                }
            } else {
                current_statement_begin__ = 236;
                stan::math::assign(tmp_lik, 0);
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 193;
            size_t Rsig2_i_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t i_0__ = 0; i_0__ < Rsig2_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Rsig2[i_0__]", Rsig2[i_0__], 0);
            }
            // write transformed parameters
            if (include_tparams__) {
                vars__.push_back(R0);
                size_t Ysig2_k_0_max__ = (has_mis_SE ? 1 : 0 );
                for (size_t k_0__ = 0; k_0__ < Ysig2_k_0_max__; ++k_0__) {
                    vars__.push_back(Ysig2[k_0__]);
                }
                size_t SE_j_1_max__ = n;
                for (size_t j_1__ = 0; j_1__ < SE_j_1_max__; ++j_1__) {
                    vars__.push_back(SE(j_1__));
                }
                size_t Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
                for (size_t k_0__ = 0; k_0__ < Rsig2_k_0_max__; ++k_0__) {
                    vars__.push_back(Rsig2[k_0__]);
                }
                size_t Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
                for (size_t k_0__ = 0; k_0__ < Rmu_k_0_max__; ++k_0__) {
                    vars__.push_back(Rmu[k_0__]);
                }
                size_t R_j_1_max__ = e;
                for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                    vars__.push_back(R(j_1__));
                }
                vars__.push_back(tmp_lik);
                size_t tmp_mu_j_1_max__ = e;
                for (size_t j_1__ = 0; j_1__ < tmp_mu_j_1_max__; ++j_1__) {
                    vars__.push_back(tmp_mu(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 252;
            double lik;
            (void) lik;  // dummy to suppress unused var warning
            stan::math::initialize(lik, DUMMY_VAR__);
            stan::math::fill(lik, DUMMY_VAR__);
            current_statement_begin__ = 253;
            double prior;
            (void) prior;  // dummy to suppress unused var warning
            stan::math::initialize(prior, DUMMY_VAR__);
            stan::math::fill(prior, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 256;
            if (as_bool(lik_pow_ind)) {
                current_statement_begin__ = 257;
                stan::math::assign(lik, (tmp_lik + lik_const));
            } else {
                current_statement_begin__ = 259;
                stan::math::assign(lik, (prune(n, prune_T, des_e, tip_e, real_e, postorder, mis_code, which_non_mis, X, SE, R, pstream__) + lik_const));
                current_statement_begin__ = 262;
                if (as_bool(has_contra)) {
                    current_statement_begin__ = 263;
                    stan::math::assign(lik, (lik + (-(0.5) * ((sum_sq_scale_contra / get_base1(Ysig2, 1, "Ysig2", 1)) + (n_contra * stan::math::log(get_base1(Ysig2, 1, "Ysig2", 1)))))));
                }
            }
            current_statement_begin__ = 268;
            stan::math::assign(prior, cauchy_log(R0, R0_prior_mu, R0_prior_sig));
            current_statement_begin__ = 269;
            if (as_bool(has_contra)) {
                current_statement_begin__ = 270;
                stan::math::assign(prior, (prior + (cauchy_log(Ysig2, 0, Ysig2_prior_sig) + stan::math::log(2))));
            }
            current_statement_begin__ = 272;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 273;
                stan::math::assign(prior, (prior + (cauchy_log(get_base1(Rsig2, 1, "Rsig2", 1), 0, Rsig2_prior_sig) + stan::math::log(2))));
                current_statement_begin__ = 274;
                stan::math::assign(prior, (prior + multi_normal_cholesky_log(R, tmp_mu, multiply(stan::math::sqrt(get_base1(Rsig2, 1, "Rsig2", 1)), chol_eV))));
            }
            current_statement_begin__ = 276;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 277;
                stan::math::assign(prior, (prior + cauchy_log(get_base1(Rmu, 1, "Rmu", 1), Rmu_prior_mu, Rmu_prior_sig)));
            }
            // validate, write generated quantities
            current_statement_begin__ = 252;
            vars__.push_back(lik);
            current_statement_begin__ = 253;
            vars__.push_back(prior);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_univar_evorates";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "std_R0";
        param_names__.push_back(param_name_stream__.str());
        size_t std_Ysig2_k_0_max__ = (has_mis_SE ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < std_Ysig2_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Ysig2" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t std_Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rsig2_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Rsig2" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t std_Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rmu_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Rmu" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t raw_R_j_1_max__ = (constr_Rsig2 ? 0 : e );
        for (size_t j_1__ = 0; j_1__ < raw_R_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "raw_R" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "R0";
            param_names__.push_back(param_name_stream__.str());
            size_t Ysig2_k_0_max__ = (has_mis_SE ? 1 : 0 );
            for (size_t k_0__ = 0; k_0__ < Ysig2_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Ysig2" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t SE_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < SE_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "SE" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rsig2_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rsig2" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rmu_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rmu" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t R_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "R" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "tmp_lik";
            param_names__.push_back(param_name_stream__.str());
            size_t tmp_mu_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < tmp_mu_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tmp_mu" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "lik";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "prior";
        param_names__.push_back(param_name_stream__.str());
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "std_R0";
        param_names__.push_back(param_name_stream__.str());
        size_t std_Ysig2_k_0_max__ = (has_mis_SE ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < std_Ysig2_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Ysig2" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t std_Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rsig2_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Rsig2" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t std_Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rmu_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Rmu" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t raw_R_j_1_max__ = (constr_Rsig2 ? 0 : e );
        for (size_t j_1__ = 0; j_1__ < raw_R_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "raw_R" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "R0";
            param_names__.push_back(param_name_stream__.str());
            size_t Ysig2_k_0_max__ = (has_mis_SE ? 1 : 0 );
            for (size_t k_0__ = 0; k_0__ < Ysig2_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Ysig2" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t SE_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < SE_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "SE" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rsig2_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rsig2" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rmu_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rmu" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t R_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "R" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "tmp_lik";
            param_names__.push_back(param_name_stream__.str());
            size_t tmp_mu_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < tmp_mu_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tmp_mu" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "lik";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "prior";
        param_names__.push_back(param_name_stream__.str());
    }
}; // model
}  // namespace
typedef model_univar_evorates_namespace::model_univar_evorates stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
