// Generated by rstantools.  Do not edit by hand.

/*
    contSimmap is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    contSimmap is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with contSimmap.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_univar_corateBM_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_univar_corateBM");
    reader.add_event(191, 189, "end", "model_univar_corateBM");
    return reader;
}
template <typename T1__, typename T2__>
Eigen::Matrix<typename boost::math::tools::promote_args<T1__, T2__>::type, Eigen::Dynamic, 1>
get_X(const int& n,
          const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& Y,
          const Eigen::Matrix<T2__, Eigen::Dynamic, 1>& mis_Y,
          const std::vector<int>& which_mis, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 4;
        validate_non_negative_index("X", "n", n);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> X(n);
        stan::math::initialize(X, DUMMY_VAR__);
        stan::math::fill(X, DUMMY_VAR__);
        current_statement_begin__ = 5;
        stan::math::assign(X, Y);
        current_statement_begin__ = 6;
        stan::model::assign(X, 
                    stan::model::cons_list(stan::model::index_multi(which_mis), stan::model::nil_index_list()), 
                    mis_Y, 
                    "assigning variable X");
        current_statement_begin__ = 7;
        return stan::math::promote_scalar<fun_return_scalar_t__>(X);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct get_X_functor__ {
    template <typename T1__, typename T2__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T1__, T2__>::type, Eigen::Dynamic, 1>
    operator()(const int& n,
          const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& Y,
          const Eigen::Matrix<T2__, Eigen::Dynamic, 1>& mis_Y,
          const std::vector<int>& which_mis, std::ostream* pstream__) const {
        return get_X(n, Y, mis_Y, which_mis, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_univar_corateBM
  : public stan::model::model_base_crtp<model_univar_corateBM> {
private:
        int n;
        int e;
        vector_d Y;
        matrix_d eV;
        int k_mis;
        std::vector<int> which_mis;
        int n_tp;
        std::vector<int> which_tp;
        vector_d tp_mu;
        vector_d tp_sig;
        vector_d prune_T;
        std::vector<std::vector<int> > des_e;
        std::vector<int> tip_e;
        std::vector<int> real_e;
        std::vector<int> postorder;
        double R0_prior_mu;
        double R0_prior_sig;
        double Rsig2_prior;
        double X0_prior_mu;
        double X0_prior_sig;
        double Rmu_prior_mu;
        double Rmu_prior_sig;
        int constr_Rsig2;
        int constr_Rmu;
        double lik_power;
        matrix_d chol_eV;
        vector_d T_midpts;
        int lik_pow_ind;
        int has_tp;
public:
    model_univar_corateBM(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_univar_corateBM(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_univar_corateBM_namespace::model_univar_corateBM";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "e", "int", context__.to_vec());
            e = int(0);
            vals_i__ = context__.vals_i("e");
            pos__ = 0;
            e = vals_i__[pos__++];
            current_statement_begin__ = 15;
            validate_non_negative_index("Y", "n", n);
            context__.validate_dims("data initialization", "Y", "vector_d", context__.to_vec(n));
            Y = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("Y");
            pos__ = 0;
            size_t Y_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < Y_j_1_max__; ++j_1__) {
                Y(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 16;
            validate_non_negative_index("eV", "e", e);
            validate_non_negative_index("eV", "e", e);
            context__.validate_dims("data initialization", "eV", "matrix_d", context__.to_vec(e,e));
            eV = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(e, e);
            vals_r__ = context__.vals_r("eV");
            pos__ = 0;
            size_t eV_j_2_max__ = e;
            size_t eV_j_1_max__ = e;
            for (size_t j_2__ = 0; j_2__ < eV_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < eV_j_1_max__; ++j_1__) {
                    eV(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 20;
            context__.validate_dims("data initialization", "k_mis", "int", context__.to_vec());
            k_mis = int(0);
            vals_i__ = context__.vals_i("k_mis");
            pos__ = 0;
            k_mis = vals_i__[pos__++];
            current_statement_begin__ = 21;
            validate_non_negative_index("which_mis", "k_mis", k_mis);
            context__.validate_dims("data initialization", "which_mis", "int", context__.to_vec(k_mis));
            which_mis = std::vector<int>(k_mis, int(0));
            vals_i__ = context__.vals_i("which_mis");
            pos__ = 0;
            size_t which_mis_k_0_max__ = k_mis;
            for (size_t k_0__ = 0; k_0__ < which_mis_k_0_max__; ++k_0__) {
                which_mis[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 25;
            context__.validate_dims("data initialization", "n_tp", "int", context__.to_vec());
            n_tp = int(0);
            vals_i__ = context__.vals_i("n_tp");
            pos__ = 0;
            n_tp = vals_i__[pos__++];
            current_statement_begin__ = 26;
            validate_non_negative_index("which_tp", "n_tp", n_tp);
            context__.validate_dims("data initialization", "which_tp", "int", context__.to_vec(n_tp));
            which_tp = std::vector<int>(n_tp, int(0));
            vals_i__ = context__.vals_i("which_tp");
            pos__ = 0;
            size_t which_tp_k_0_max__ = n_tp;
            for (size_t k_0__ = 0; k_0__ < which_tp_k_0_max__; ++k_0__) {
                which_tp[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 27;
            validate_non_negative_index("tp_mu", "n_tp", n_tp);
            context__.validate_dims("data initialization", "tp_mu", "vector_d", context__.to_vec(n_tp));
            tp_mu = Eigen::Matrix<double, Eigen::Dynamic, 1>(n_tp);
            vals_r__ = context__.vals_r("tp_mu");
            pos__ = 0;
            size_t tp_mu_j_1_max__ = n_tp;
            for (size_t j_1__ = 0; j_1__ < tp_mu_j_1_max__; ++j_1__) {
                tp_mu(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 28;
            validate_non_negative_index("tp_sig", "n_tp", n_tp);
            context__.validate_dims("data initialization", "tp_sig", "vector_d", context__.to_vec(n_tp));
            tp_sig = Eigen::Matrix<double, Eigen::Dynamic, 1>(n_tp);
            vals_r__ = context__.vals_r("tp_sig");
            pos__ = 0;
            size_t tp_sig_j_1_max__ = n_tp;
            for (size_t j_1__ = 0; j_1__ < tp_sig_j_1_max__; ++j_1__) {
                tp_sig(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 32;
            validate_non_negative_index("prune_T", "((2 * n) - 1)", ((2 * n) - 1));
            context__.validate_dims("data initialization", "prune_T", "vector_d", context__.to_vec(((2 * n) - 1)));
            prune_T = Eigen::Matrix<double, Eigen::Dynamic, 1>(((2 * n) - 1));
            vals_r__ = context__.vals_r("prune_T");
            pos__ = 0;
            size_t prune_T_j_1_max__ = ((2 * n) - 1);
            for (size_t j_1__ = 0; j_1__ < prune_T_j_1_max__; ++j_1__) {
                prune_T(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 33;
            validate_non_negative_index("des_e", "((2 * n) - 1)", ((2 * n) - 1));
            validate_non_negative_index("des_e", "2", 2);
            context__.validate_dims("data initialization", "des_e", "int", context__.to_vec(((2 * n) - 1),2));
            des_e = std::vector<std::vector<int> >(((2 * n) - 1), std::vector<int>(2, int(0)));
            vals_i__ = context__.vals_i("des_e");
            pos__ = 0;
            size_t des_e_k_0_max__ = ((2 * n) - 1);
            size_t des_e_k_1_max__ = 2;
            for (size_t k_1__ = 0; k_1__ < des_e_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < des_e_k_0_max__; ++k_0__) {
                    des_e[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 34;
            validate_non_negative_index("tip_e", "n", n);
            context__.validate_dims("data initialization", "tip_e", "int", context__.to_vec(n));
            tip_e = std::vector<int>(n, int(0));
            vals_i__ = context__.vals_i("tip_e");
            pos__ = 0;
            size_t tip_e_k_0_max__ = n;
            for (size_t k_0__ = 0; k_0__ < tip_e_k_0_max__; ++k_0__) {
                tip_e[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 35;
            validate_non_negative_index("real_e", "e", e);
            context__.validate_dims("data initialization", "real_e", "int", context__.to_vec(e));
            real_e = std::vector<int>(e, int(0));
            vals_i__ = context__.vals_i("real_e");
            pos__ = 0;
            size_t real_e_k_0_max__ = e;
            for (size_t k_0__ = 0; k_0__ < real_e_k_0_max__; ++k_0__) {
                real_e[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 36;
            validate_non_negative_index("postorder", "(n - 1)", (n - 1));
            context__.validate_dims("data initialization", "postorder", "int", context__.to_vec((n - 1)));
            postorder = std::vector<int>((n - 1), int(0));
            vals_i__ = context__.vals_i("postorder");
            pos__ = 0;
            size_t postorder_k_0_max__ = (n - 1);
            for (size_t k_0__ = 0; k_0__ < postorder_k_0_max__; ++k_0__) {
                postorder[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 40;
            context__.validate_dims("data initialization", "R0_prior_mu", "double", context__.to_vec());
            R0_prior_mu = double(0);
            vals_r__ = context__.vals_r("R0_prior_mu");
            pos__ = 0;
            R0_prior_mu = vals_r__[pos__++];
            current_statement_begin__ = 41;
            context__.validate_dims("data initialization", "R0_prior_sig", "double", context__.to_vec());
            R0_prior_sig = double(0);
            vals_r__ = context__.vals_r("R0_prior_sig");
            pos__ = 0;
            R0_prior_sig = vals_r__[pos__++];
            current_statement_begin__ = 42;
            context__.validate_dims("data initialization", "Rsig2_prior", "double", context__.to_vec());
            Rsig2_prior = double(0);
            vals_r__ = context__.vals_r("Rsig2_prior");
            pos__ = 0;
            Rsig2_prior = vals_r__[pos__++];
            current_statement_begin__ = 43;
            context__.validate_dims("data initialization", "X0_prior_mu", "double", context__.to_vec());
            X0_prior_mu = double(0);
            vals_r__ = context__.vals_r("X0_prior_mu");
            pos__ = 0;
            X0_prior_mu = vals_r__[pos__++];
            current_statement_begin__ = 44;
            context__.validate_dims("data initialization", "X0_prior_sig", "double", context__.to_vec());
            X0_prior_sig = double(0);
            vals_r__ = context__.vals_r("X0_prior_sig");
            pos__ = 0;
            X0_prior_sig = vals_r__[pos__++];
            current_statement_begin__ = 45;
            context__.validate_dims("data initialization", "Rmu_prior_mu", "double", context__.to_vec());
            Rmu_prior_mu = double(0);
            vals_r__ = context__.vals_r("Rmu_prior_mu");
            pos__ = 0;
            Rmu_prior_mu = vals_r__[pos__++];
            current_statement_begin__ = 46;
            context__.validate_dims("data initialization", "Rmu_prior_sig", "double", context__.to_vec());
            Rmu_prior_sig = double(0);
            vals_r__ = context__.vals_r("Rmu_prior_sig");
            pos__ = 0;
            Rmu_prior_sig = vals_r__[pos__++];
            current_statement_begin__ = 50;
            context__.validate_dims("data initialization", "constr_Rsig2", "int", context__.to_vec());
            constr_Rsig2 = int(0);
            vals_i__ = context__.vals_i("constr_Rsig2");
            pos__ = 0;
            constr_Rsig2 = vals_i__[pos__++];
            current_statement_begin__ = 51;
            context__.validate_dims("data initialization", "constr_Rmu", "int", context__.to_vec());
            constr_Rmu = int(0);
            vals_i__ = context__.vals_i("constr_Rmu");
            pos__ = 0;
            constr_Rmu = vals_i__[pos__++];
            current_statement_begin__ = 55;
            context__.validate_dims("data initialization", "lik_power", "double", context__.to_vec());
            lik_power = double(0);
            vals_r__ = context__.vals_r("lik_power");
            pos__ = 0;
            lik_power = vals_r__[pos__++];
            // initialize transformed data variables
            current_statement_begin__ = 59;
            validate_non_negative_index("chol_eV", "(constr_Rsig2 ? 0 : e )", (constr_Rsig2 ? 0 : e ));
            validate_non_negative_index("chol_eV", "(constr_Rsig2 ? 0 : e )", (constr_Rsig2 ? 0 : e ));
            chol_eV = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>((constr_Rsig2 ? 0 : e ), (constr_Rsig2 ? 0 : e ));
            stan::math::fill(chol_eV, DUMMY_VAR__);
            current_statement_begin__ = 60;
            validate_non_negative_index("T_midpts", "(constr_Rmu ? 0 : e )", (constr_Rmu ? 0 : e ));
            T_midpts = Eigen::Matrix<double, Eigen::Dynamic, 1>((constr_Rmu ? 0 : e ));
            stan::math::fill(T_midpts, DUMMY_VAR__);
            current_statement_begin__ = 61;
            lik_pow_ind = int(0);
            stan::math::fill(lik_pow_ind, std::numeric_limits<int>::min());
            current_statement_begin__ = 62;
            has_tp = int(0);
            stan::math::fill(has_tp, std::numeric_limits<int>::min());
            // execute transformed data statements
            current_statement_begin__ = 66;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 67;
                stan::math::assign(chol_eV, cholesky_decompose(eV));
            }
            current_statement_begin__ = 69;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 70;
                stan::math::assign(T_midpts, add(diagonal(eV), divide(stan::model::rvalue(prune_T, stan::model::cons_list(stan::model::index_multi(real_e), stan::model::nil_index_list()), "prune_T"), 6)));
            }
            current_statement_begin__ = 74;
            if (as_bool(logical_eq(lik_power, 0))) {
                current_statement_begin__ = 75;
                stan::math::assign(lik_pow_ind, 0);
            } else {
                current_statement_begin__ = 77;
                stan::math::assign(lik_pow_ind, 1);
            }
            current_statement_begin__ = 79;
            if (as_bool(logical_eq(n_tp, 0))) {
                current_statement_begin__ = 80;
                stan::math::assign(has_tp, 0);
            } else {
                current_statement_begin__ = 82;
                stan::math::assign(has_tp, 1);
            }
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 88;
            num_params_r__ += 1;
            current_statement_begin__ = 89;
            num_params_r__ += 1;
            current_statement_begin__ = 90;
            validate_non_negative_index("std_Rsig2", "(constr_Rsig2 ? 0 : 1 )", (constr_Rsig2 ? 0 : 1 ));
            num_params_r__ += (1 * (constr_Rsig2 ? 0 : 1 ));
            current_statement_begin__ = 91;
            validate_non_negative_index("std_Rmu", "(constr_Rmu ? 0 : 1 )", (constr_Rmu ? 0 : 1 ));
            num_params_r__ += (1 * (constr_Rmu ? 0 : 1 ));
            current_statement_begin__ = 92;
            validate_non_negative_index("raw_R", "(constr_Rsig2 ? 0 : e )", (constr_Rsig2 ? 0 : e ));
            num_params_r__ += (constr_Rsig2 ? 0 : e );
            current_statement_begin__ = 95;
            validate_non_negative_index("mis_Y", "(lik_pow_ind ? k_mis : 0 )", (lik_pow_ind ? k_mis : 0 ));
            num_params_r__ += (lik_pow_ind ? k_mis : 0 );
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_univar_corateBM() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 88;
        if (!(context__.contains_r("std_R0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable std_R0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("std_R0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "std_R0", "double", context__.to_vec());
        double std_R0(0);
        std_R0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(std_R0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable std_R0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 89;
        if (!(context__.contains_r("std_X0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable std_X0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("std_X0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "std_X0", "double", context__.to_vec());
        double std_X0(0);
        std_X0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(std_X0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable std_X0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 90;
        if (!(context__.contains_r("std_Rsig2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable std_Rsig2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("std_Rsig2");
        pos__ = 0U;
        validate_non_negative_index("std_Rsig2", "(constr_Rsig2 ? 0 : 1 )", (constr_Rsig2 ? 0 : 1 ));
        context__.validate_dims("parameter initialization", "std_Rsig2", "double", context__.to_vec((constr_Rsig2 ? 0 : 1 )));
        std::vector<double> std_Rsig2((constr_Rsig2 ? 0 : 1 ), double(0));
        size_t std_Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rsig2_k_0_max__; ++k_0__) {
            std_Rsig2[k_0__] = vals_r__[pos__++];
        }
        size_t std_Rsig2_i_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t i_0__ = 0; i_0__ < std_Rsig2_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, std_Rsig2[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable std_Rsig2: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 91;
        if (!(context__.contains_r("std_Rmu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable std_Rmu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("std_Rmu");
        pos__ = 0U;
        validate_non_negative_index("std_Rmu", "(constr_Rmu ? 0 : 1 )", (constr_Rmu ? 0 : 1 ));
        context__.validate_dims("parameter initialization", "std_Rmu", "double", context__.to_vec((constr_Rmu ? 0 : 1 )));
        std::vector<double> std_Rmu((constr_Rmu ? 0 : 1 ), double(0));
        size_t std_Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rmu_k_0_max__; ++k_0__) {
            std_Rmu[k_0__] = vals_r__[pos__++];
        }
        size_t std_Rmu_i_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t i_0__ = 0; i_0__ < std_Rmu_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_unconstrain(std_Rmu[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable std_Rmu: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 92;
        if (!(context__.contains_r("raw_R")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable raw_R missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("raw_R");
        pos__ = 0U;
        validate_non_negative_index("raw_R", "(constr_Rsig2 ? 0 : e )", (constr_Rsig2 ? 0 : e ));
        context__.validate_dims("parameter initialization", "raw_R", "vector_d", context__.to_vec((constr_Rsig2 ? 0 : e )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> raw_R((constr_Rsig2 ? 0 : e ));
        size_t raw_R_j_1_max__ = (constr_Rsig2 ? 0 : e );
        for (size_t j_1__ = 0; j_1__ < raw_R_j_1_max__; ++j_1__) {
            raw_R(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(raw_R);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable raw_R: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 95;
        if (!(context__.contains_r("mis_Y")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mis_Y missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mis_Y");
        pos__ = 0U;
        validate_non_negative_index("mis_Y", "(lik_pow_ind ? k_mis : 0 )", (lik_pow_ind ? k_mis : 0 ));
        context__.validate_dims("parameter initialization", "mis_Y", "vector_d", context__.to_vec((lik_pow_ind ? k_mis : 0 )));
        Eigen::Matrix<double, Eigen::Dynamic, 1> mis_Y((lik_pow_ind ? k_mis : 0 ));
        size_t mis_Y_j_1_max__ = (lik_pow_ind ? k_mis : 0 );
        for (size_t j_1__ = 0; j_1__ < mis_Y_j_1_max__; ++j_1__) {
            mis_Y(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(mis_Y);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mis_Y: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 88;
            local_scalar_t__ std_R0;
            (void) std_R0;  // dummy to suppress unused var warning
            if (jacobian__)
                std_R0 = in__.scalar_constrain(lp__);
            else
                std_R0 = in__.scalar_constrain();
            current_statement_begin__ = 89;
            local_scalar_t__ std_X0;
            (void) std_X0;  // dummy to suppress unused var warning
            if (jacobian__)
                std_X0 = in__.scalar_constrain(lp__);
            else
                std_X0 = in__.scalar_constrain();
            current_statement_begin__ = 90;
            std::vector<local_scalar_t__> std_Rsig2;
            size_t std_Rsig2_d_0_max__ = (constr_Rsig2 ? 0 : 1 );
            std_Rsig2.reserve(std_Rsig2_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < std_Rsig2_d_0_max__; ++d_0__) {
                if (jacobian__)
                    std_Rsig2.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    std_Rsig2.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 91;
            std::vector<local_scalar_t__> std_Rmu;
            size_t std_Rmu_d_0_max__ = (constr_Rmu ? 0 : 1 );
            std_Rmu.reserve(std_Rmu_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < std_Rmu_d_0_max__; ++d_0__) {
                if (jacobian__)
                    std_Rmu.push_back(in__.scalar_constrain(lp__));
                else
                    std_Rmu.push_back(in__.scalar_constrain());
            }
            current_statement_begin__ = 92;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> raw_R;
            (void) raw_R;  // dummy to suppress unused var warning
            if (jacobian__)
                raw_R = in__.vector_constrain((constr_Rsig2 ? 0 : e ), lp__);
            else
                raw_R = in__.vector_constrain((constr_Rsig2 ? 0 : e ));
            current_statement_begin__ = 95;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> mis_Y;
            (void) mis_Y;  // dummy to suppress unused var warning
            if (jacobian__)
                mis_Y = in__.vector_constrain((lik_pow_ind ? k_mis : 0 ), lp__);
            else
                mis_Y = in__.vector_constrain((lik_pow_ind ? k_mis : 0 ));
            // transformed parameters
            current_statement_begin__ = 99;
            local_scalar_t__ R0;
            (void) R0;  // dummy to suppress unused var warning
            stan::math::initialize(R0, DUMMY_VAR__);
            stan::math::fill(R0, DUMMY_VAR__);
            current_statement_begin__ = 100;
            local_scalar_t__ X0;
            (void) X0;  // dummy to suppress unused var warning
            stan::math::initialize(X0, DUMMY_VAR__);
            stan::math::fill(X0, DUMMY_VAR__);
            current_statement_begin__ = 101;
            validate_non_negative_index("Rsig2", "(constr_Rsig2 ? 0 : 1 )", (constr_Rsig2 ? 0 : 1 ));
            std::vector<local_scalar_t__> Rsig2((constr_Rsig2 ? 0 : 1 ), local_scalar_t__(0));
            stan::math::initialize(Rsig2, DUMMY_VAR__);
            stan::math::fill(Rsig2, DUMMY_VAR__);
            current_statement_begin__ = 102;
            validate_non_negative_index("Rmu", "(constr_Rmu ? 0 : 1 )", (constr_Rmu ? 0 : 1 ));
            std::vector<local_scalar_t__> Rmu((constr_Rmu ? 0 : 1 ), local_scalar_t__(0));
            stan::math::initialize(Rmu, DUMMY_VAR__);
            stan::math::fill(Rmu, DUMMY_VAR__);
            current_statement_begin__ = 103;
            validate_non_negative_index("R", "e", e);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> R(e);
            stan::math::initialize(R, DUMMY_VAR__);
            stan::math::fill(R, DUMMY_VAR__);
            current_statement_begin__ = 104;
            validate_non_negative_index("trans_tp", "n_tp", n_tp);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> trans_tp(n_tp);
            stan::math::initialize(trans_tp, DUMMY_VAR__);
            stan::math::fill(trans_tp, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 108;
            stan::math::assign(R0, (R0_prior_mu + (R0_prior_sig * std_R0)));
            current_statement_begin__ = 109;
            stan::math::assign(X0, (X0_prior_mu + (X0_prior_sig * std_X0)));
            current_statement_begin__ = 110;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 111;
                stan::model::assign(Rsig2, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Rsig2_prior * get_base1(std_Rsig2, 1, "std_Rsig2", 1)), 
                            "assigning variable Rsig2");
            }
            current_statement_begin__ = 113;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 114;
                stan::model::assign(Rmu, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Rmu_prior_mu + (Rmu_prior_sig * get_base1(std_Rmu, 1, "std_Rmu", 1))), 
                            "assigning variable Rmu");
            }
            current_statement_begin__ = 119;
            stan::math::assign(R, rep_vector(R0, e));
            current_statement_begin__ = 120;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 121;
                stan::math::assign(R, add(R, multiply(get_base1(Rmu, 1, "Rmu", 1), T_midpts)));
            }
            current_statement_begin__ = 123;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 124;
                stan::math::assign(R, add(R, multiply(multiply(stan::math::sqrt(get_base1(Rsig2, 1, "Rsig2", 1)), chol_eV), raw_R)));
            }
            current_statement_begin__ = 129;
            if (as_bool((primitive_value(has_tp) && primitive_value(lik_pow_ind)))) {
                current_statement_begin__ = 130;
                stan::math::assign(trans_tp, elt_divide(subtract(stan::model::rvalue(mis_Y, stan::model::cons_list(stan::model::index_multi(which_tp), stan::model::nil_index_list()), "mis_Y"), tp_mu), tp_sig));
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 99;
            if (stan::math::is_uninitialized(R0)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: R0";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable R0: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 100;
            if (stan::math::is_uninitialized(X0)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: X0";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable X0: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 101;
            size_t Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rsig2_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(Rsig2[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: Rsig2" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Rsig2: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            size_t Rsig2_i_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t i_0__ = 0; i_0__ < Rsig2_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Rsig2[i_0__]", Rsig2[i_0__], 0);
            }
            current_statement_begin__ = 102;
            size_t Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rmu_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(Rmu[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: Rmu" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Rmu: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 103;
            size_t R_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(R(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: R" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable R: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 104;
            size_t trans_tp_j_1_max__ = n_tp;
            for (size_t j_1__ = 0; j_1__ < trans_tp_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(trans_tp(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: trans_tp" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable trans_tp: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            current_statement_begin__ = 136;
            lp_accum__.add(std_normal_log<propto__>(std_R0));
            current_statement_begin__ = 137;
            lp_accum__.add(std_normal_log<propto__>(std_X0));
            current_statement_begin__ = 138;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 139;
                lp_accum__.add(std_normal_log<propto__>(get_base1(std_Rsig2, 1, "std_Rsig2", 1)));
            }
            current_statement_begin__ = 141;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 142;
                lp_accum__.add(std_normal_log<propto__>(get_base1(std_Rmu, 1, "std_Rmu", 1)));
            }
            current_statement_begin__ = 147;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 148;
                lp_accum__.add(std_normal_log<propto__>(raw_R));
            }
            current_statement_begin__ = 153;
            if (as_bool(lik_pow_ind)) {
                current_statement_begin__ = 156;
                if (as_bool(logical_neq(has_tp, 0))) {
                    current_statement_begin__ = 157;
                    lp_accum__.add(((-(0.5) * lik_power) * dot_self(trans_tp)));
                }
                {
                current_statement_begin__ = 160;
                validate_non_negative_index("SS", "((2 * n) - 1)", ((2 * n) - 1));
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> SS(((2 * n) - 1));
                stan::math::initialize(SS, DUMMY_VAR__);
                stan::math::fill(SS, DUMMY_VAR__);
                current_statement_begin__ = 161;
                validate_non_negative_index("XX", "((2 * n) - 1)", ((2 * n) - 1));
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> XX(((2 * n) - 1));
                stan::math::initialize(XX, DUMMY_VAR__);
                stan::math::fill(XX, DUMMY_VAR__);
                current_statement_begin__ = 162;
                validate_non_negative_index("VV", "((2 * n) - 1)", ((2 * n) - 1));
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> VV(((2 * n) - 1));
                stan::math::initialize(VV, DUMMY_VAR__);
                stan::math::fill(VV, DUMMY_VAR__);
                current_statement_begin__ = 163;
                validate_non_negative_index("LL", "(n - 1)", (n - 1));
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> LL((n - 1));
                stan::math::initialize(LL, DUMMY_VAR__);
                stan::math::fill(LL, DUMMY_VAR__);
                current_statement_begin__ = 164;
                int counter(0);
                (void) counter;  // dummy to suppress unused var warning
                stan::math::fill(counter, std::numeric_limits<int>::min());
                current_statement_begin__ = 165;
                validate_non_negative_index("des_X", "2", 2);
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> des_X(2);
                stan::math::initialize(des_X, DUMMY_VAR__);
                stan::math::fill(des_X, DUMMY_VAR__);
                current_statement_begin__ = 166;
                validate_non_negative_index("des_V", "2", 2);
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> des_V(2);
                stan::math::initialize(des_V, DUMMY_VAR__);
                stan::math::fill(des_V, DUMMY_VAR__);
                current_statement_begin__ = 167;
                local_scalar_t__ sum_des_V(DUMMY_VAR__);
                (void) sum_des_V;  // dummy to suppress unused var warning
                stan::math::initialize(sum_des_V, DUMMY_VAR__);
                stan::math::fill(sum_des_V, DUMMY_VAR__);
                current_statement_begin__ = 168;
                stan::math::assign(SS, rep_vector(0, ((2 * n) - 1)));
                current_statement_begin__ = 169;
                stan::model::assign(SS, 
                            stan::model::cons_list(stan::model::index_multi(real_e), stan::model::nil_index_list()), 
                            elt_multiply(stan::model::rvalue(prune_T, stan::model::cons_list(stan::model::index_multi(real_e), stan::model::nil_index_list()), "prune_T"), stan::math::exp(R)), 
                            "assigning variable SS");
                current_statement_begin__ = 170;
                stan::model::assign(XX, 
                            stan::model::cons_list(stan::model::index_multi(tip_e), stan::model::nil_index_list()), 
                            get_X(n, Y, mis_Y, which_mis, pstream__), 
                            "assigning variable XX");
                current_statement_begin__ = 171;
                stan::model::assign(VV, 
                            stan::model::cons_list(stan::model::index_multi(tip_e), stan::model::nil_index_list()), 
                            rep_vector(0, n), 
                            "assigning variable VV");
                current_statement_begin__ = 172;
                stan::math::assign(counter, 0);
                current_statement_begin__ = 173;
                for (auto& i : postorder) {
                    (void) i;  // dummy to suppress unused var warning
                    current_statement_begin__ = 174;
                    stan::math::assign(des_X, stan::model::rvalue(XX, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(des_e, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "des_e")), stan::model::nil_index_list()), "XX"));
                    current_statement_begin__ = 175;
                    stan::math::assign(des_V, add(stan::model::rvalue(VV, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(des_e, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "des_e")), stan::model::nil_index_list()), "VV"), stan::model::rvalue(SS, stan::model::cons_list(stan::model::index_multi(stan::model::rvalue(des_e, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "des_e")), stan::model::nil_index_list()), "SS")));
                    current_statement_begin__ = 176;
                    stan::math::assign(sum_des_V, sum(des_V));
                    current_statement_begin__ = 177;
                    stan::math::assign(counter, (counter + 1));
                    current_statement_begin__ = 178;
                    stan::model::assign(LL, 
                                stan::model::cons_list(stan::model::index_uni(counter), stan::model::nil_index_list()), 
                                (-(0.5) * (stan::math::log(sum_des_V) + (pow((get_base1(des_X, 1, "des_X", 1) - get_base1(des_X, 2, "des_X", 1)), 2) / sum_des_V))), 
                                "assigning variable LL");
                    current_statement_begin__ = 179;
                    stan::model::assign(XX, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (((get_base1(des_V, 2, "des_V", 1) / sum_des_V) * get_base1(des_X, 1, "des_X", 1)) + ((get_base1(des_V, 1, "des_V", 1) / sum_des_V) * get_base1(des_X, 2, "des_X", 1))), 
                                "assigning variable XX");
                    current_statement_begin__ = 181;
                    if (as_bool((primitive_value(logical_eq(get_base1(des_V, 1, "des_V", 1), 0)) || primitive_value(logical_eq(get_base1(des_V, 2, "des_V", 1), 0))))) {
                        current_statement_begin__ = 182;
                        stan::model::assign(VV, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                    0, 
                                    "assigning variable VV");
                    } else {
                        current_statement_begin__ = 184;
                        stan::model::assign(VV, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                    (1 / ((1 / get_base1(des_V, 1, "des_V", 1)) + (1 / get_base1(des_V, 2, "des_V", 1)))), 
                                    "assigning variable VV");
                    }
                }
                current_statement_begin__ = 187;
                lp_accum__.add((lik_power * (sum(LL) - (0.5 * (stan::math::log(get_base1(VV, 1, "VV", 1)) + (pow((X0 - get_base1(XX, 1, "XX", 1)), 2) / get_base1(VV, 1, "VV", 1)))))));
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("std_R0");
        names__.push_back("std_X0");
        names__.push_back("std_Rsig2");
        names__.push_back("std_Rmu");
        names__.push_back("raw_R");
        names__.push_back("mis_Y");
        names__.push_back("R0");
        names__.push_back("X0");
        names__.push_back("Rsig2");
        names__.push_back("Rmu");
        names__.push_back("R");
        names__.push_back("trans_tp");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rsig2 ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rmu ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rsig2 ? 0 : e ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((lik_pow_ind ? k_mis : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rsig2 ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((constr_Rmu ? 0 : 1 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(e);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_tp);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_univar_corateBM_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double std_R0 = in__.scalar_constrain();
        vars__.push_back(std_R0);
        double std_X0 = in__.scalar_constrain();
        vars__.push_back(std_X0);
        std::vector<double> std_Rsig2;
        size_t std_Rsig2_d_0_max__ = (constr_Rsig2 ? 0 : 1 );
        std_Rsig2.reserve(std_Rsig2_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < std_Rsig2_d_0_max__; ++d_0__) {
            std_Rsig2.push_back(in__.scalar_lb_constrain(0));
        }
        size_t std_Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rsig2_k_0_max__; ++k_0__) {
            vars__.push_back(std_Rsig2[k_0__]);
        }
        std::vector<double> std_Rmu;
        size_t std_Rmu_d_0_max__ = (constr_Rmu ? 0 : 1 );
        std_Rmu.reserve(std_Rmu_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < std_Rmu_d_0_max__; ++d_0__) {
            std_Rmu.push_back(in__.scalar_constrain());
        }
        size_t std_Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rmu_k_0_max__; ++k_0__) {
            vars__.push_back(std_Rmu[k_0__]);
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> raw_R = in__.vector_constrain((constr_Rsig2 ? 0 : e ));
        size_t raw_R_j_1_max__ = (constr_Rsig2 ? 0 : e );
        for (size_t j_1__ = 0; j_1__ < raw_R_j_1_max__; ++j_1__) {
            vars__.push_back(raw_R(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> mis_Y = in__.vector_constrain((lik_pow_ind ? k_mis : 0 ));
        size_t mis_Y_j_1_max__ = (lik_pow_ind ? k_mis : 0 );
        for (size_t j_1__ = 0; j_1__ < mis_Y_j_1_max__; ++j_1__) {
            vars__.push_back(mis_Y(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 99;
            double R0;
            (void) R0;  // dummy to suppress unused var warning
            stan::math::initialize(R0, DUMMY_VAR__);
            stan::math::fill(R0, DUMMY_VAR__);
            current_statement_begin__ = 100;
            double X0;
            (void) X0;  // dummy to suppress unused var warning
            stan::math::initialize(X0, DUMMY_VAR__);
            stan::math::fill(X0, DUMMY_VAR__);
            current_statement_begin__ = 101;
            validate_non_negative_index("Rsig2", "(constr_Rsig2 ? 0 : 1 )", (constr_Rsig2 ? 0 : 1 ));
            std::vector<double> Rsig2((constr_Rsig2 ? 0 : 1 ), double(0));
            stan::math::initialize(Rsig2, DUMMY_VAR__);
            stan::math::fill(Rsig2, DUMMY_VAR__);
            current_statement_begin__ = 102;
            validate_non_negative_index("Rmu", "(constr_Rmu ? 0 : 1 )", (constr_Rmu ? 0 : 1 ));
            std::vector<double> Rmu((constr_Rmu ? 0 : 1 ), double(0));
            stan::math::initialize(Rmu, DUMMY_VAR__);
            stan::math::fill(Rmu, DUMMY_VAR__);
            current_statement_begin__ = 103;
            validate_non_negative_index("R", "e", e);
            Eigen::Matrix<double, Eigen::Dynamic, 1> R(e);
            stan::math::initialize(R, DUMMY_VAR__);
            stan::math::fill(R, DUMMY_VAR__);
            current_statement_begin__ = 104;
            validate_non_negative_index("trans_tp", "n_tp", n_tp);
            Eigen::Matrix<double, Eigen::Dynamic, 1> trans_tp(n_tp);
            stan::math::initialize(trans_tp, DUMMY_VAR__);
            stan::math::fill(trans_tp, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 108;
            stan::math::assign(R0, (R0_prior_mu + (R0_prior_sig * std_R0)));
            current_statement_begin__ = 109;
            stan::math::assign(X0, (X0_prior_mu + (X0_prior_sig * std_X0)));
            current_statement_begin__ = 110;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 111;
                stan::model::assign(Rsig2, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Rsig2_prior * get_base1(std_Rsig2, 1, "std_Rsig2", 1)), 
                            "assigning variable Rsig2");
            }
            current_statement_begin__ = 113;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 114;
                stan::model::assign(Rmu, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            (Rmu_prior_mu + (Rmu_prior_sig * get_base1(std_Rmu, 1, "std_Rmu", 1))), 
                            "assigning variable Rmu");
            }
            current_statement_begin__ = 119;
            stan::math::assign(R, rep_vector(R0, e));
            current_statement_begin__ = 120;
            if (as_bool(logical_negation(constr_Rmu))) {
                current_statement_begin__ = 121;
                stan::math::assign(R, add(R, multiply(get_base1(Rmu, 1, "Rmu", 1), T_midpts)));
            }
            current_statement_begin__ = 123;
            if (as_bool(logical_negation(constr_Rsig2))) {
                current_statement_begin__ = 124;
                stan::math::assign(R, add(R, multiply(multiply(stan::math::sqrt(get_base1(Rsig2, 1, "Rsig2", 1)), chol_eV), raw_R)));
            }
            current_statement_begin__ = 129;
            if (as_bool((primitive_value(has_tp) && primitive_value(lik_pow_ind)))) {
                current_statement_begin__ = 130;
                stan::math::assign(trans_tp, elt_divide(subtract(stan::model::rvalue(mis_Y, stan::model::cons_list(stan::model::index_multi(which_tp), stan::model::nil_index_list()), "mis_Y"), tp_mu), tp_sig));
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 101;
            size_t Rsig2_i_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t i_0__ = 0; i_0__ < Rsig2_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Rsig2[i_0__]", Rsig2[i_0__], 0);
            }
            // write transformed parameters
            if (include_tparams__) {
                vars__.push_back(R0);
                vars__.push_back(X0);
                size_t Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
                for (size_t k_0__ = 0; k_0__ < Rsig2_k_0_max__; ++k_0__) {
                    vars__.push_back(Rsig2[k_0__]);
                }
                size_t Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
                for (size_t k_0__ = 0; k_0__ < Rmu_k_0_max__; ++k_0__) {
                    vars__.push_back(Rmu[k_0__]);
                }
                size_t R_j_1_max__ = e;
                for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                    vars__.push_back(R(j_1__));
                }
                size_t trans_tp_j_1_max__ = n_tp;
                for (size_t j_1__ = 0; j_1__ < trans_tp_j_1_max__; ++j_1__) {
                    vars__.push_back(trans_tp(j_1__));
                }
            }
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_univar_corateBM";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "std_R0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "std_X0";
        param_names__.push_back(param_name_stream__.str());
        size_t std_Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rsig2_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Rsig2" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t std_Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rmu_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Rmu" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t raw_R_j_1_max__ = (constr_Rsig2 ? 0 : e );
        for (size_t j_1__ = 0; j_1__ < raw_R_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "raw_R" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t mis_Y_j_1_max__ = (lik_pow_ind ? k_mis : 0 );
        for (size_t j_1__ = 0; j_1__ < mis_Y_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mis_Y" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "R0";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "X0";
            param_names__.push_back(param_name_stream__.str());
            size_t Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rsig2_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rsig2" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rmu_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rmu" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t R_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "R" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t trans_tp_j_1_max__ = n_tp;
            for (size_t j_1__ = 0; j_1__ < trans_tp_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "trans_tp" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "std_R0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "std_X0";
        param_names__.push_back(param_name_stream__.str());
        size_t std_Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rsig2_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Rsig2" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t std_Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
        for (size_t k_0__ = 0; k_0__ < std_Rmu_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "std_Rmu" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t raw_R_j_1_max__ = (constr_Rsig2 ? 0 : e );
        for (size_t j_1__ = 0; j_1__ < raw_R_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "raw_R" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t mis_Y_j_1_max__ = (lik_pow_ind ? k_mis : 0 );
        for (size_t j_1__ = 0; j_1__ < mis_Y_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mis_Y" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "R0";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "X0";
            param_names__.push_back(param_name_stream__.str());
            size_t Rsig2_k_0_max__ = (constr_Rsig2 ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rsig2_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rsig2" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t Rmu_k_0_max__ = (constr_Rmu ? 0 : 1 );
            for (size_t k_0__ = 0; k_0__ < Rmu_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Rmu" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t R_j_1_max__ = e;
            for (size_t j_1__ = 0; j_1__ < R_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "R" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t trans_tp_j_1_max__ = n_tp;
            for (size_t j_1__ = 0; j_1__ < trans_tp_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "trans_tp" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_univar_corateBM_namespace::model_univar_corateBM stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
