#' @export
get.post.traits<-function(fit,
                      element=c('chains','quantiles','means','MAPs','diagnostics'),
                      select=NULL,select.extra=NULL,
                      stochastic=TRUE,
                      simplify=TRUE){
  if(!inherits(fit,'evorates_fit')){
    stop("fit must be a fitted evorates model (class 'evorates_fit')")
  }
  try.element<-try(match.arg(element,c('chains','quantiles','means','MAPs','diagnostics')),silent=T)
  if(inherits(try.element,'try-error')){
    stop(element," is not an available element to extract from an evorates fit: please specify one of the following: 'chains', 'quantiles', 'means', 'MAPs', or 'diagnostics'")
  }
  element<-try.element
  #deal with chain stuff
  tmp<-.expand.element(fit$chains)
  dims<-dim(tmp)
  niter<-dims[1]
  nchains<-dims[3]
  tree<-fit$call$tree
  ntips<-length(tree$tip.label)
  input<-input.evorates(tree,fit$call$trait.data,fit$call$trait.se)
  dat<-input$dat
  X<-dat$X*sqrt(input$trans.const$X_sig2)
  names(X)<-tree$tip.label
  XX<-array(NA,c(niter,nrow(tree$edge)+1,nchains))
  dimnames(XX)<-list('iterations'=NULL,
                     'parameters'=paste(colnames(fit$call$trait.data),
                                        c(tree$tip.label,ntips+1:tree$Nnode),sep='_'),
                     'chains'=dimnames(tmp)[[3]])
  PP<-XX
  LL<-XX
  XX[,1:ntips,]<-rep(X,each=niter)
  PP[,1:ntips,]<-rep((1/fit$call$trait.se)^2,each=niter)
  if(any(is.na(fit$call$trait.se))){
    Ysig2<-.int.chains(fit,'Y_sig2')
    unfixed<-(1:ntips)[is.na(fit$call$trait.se)]
    for(i in 1:nchains){
      PP[,unfixed,i]<-1/Ysig2[,1,i]
    }
    PP[,unfixed,]<-PP[,unfixed,]*rep(1/dat$inv_n_obs[unfixed],each=niter)
  }
  LL[,tree$edge[,2],]<-rep(tree$edge.length,each=niter)
  if(fit$call$constrain.Rsig2&!fit$call$trend){
    R0<-.int.chains(fit,'R_0')
    for(i in 1:nchains){
      LL[,tree$edge[,2],]<-LL[,tree$edge[,2],]*exp(R0[,1,i])
    }
  }else{
    LL[,tree$edge[,2],]<-LL[,tree$edge[,2],,drop=F]*exp(.int.chains(fit,'R_[1-9]'))
  }
  LL[,ntips+1,]<-0
  trait.chains<-.anc.recon(tree,XX,LL,PP,stochastic)
  if(!stochastic){
    trait.chains<-lapply(trait.chains,aperm,c(1,3,2))
    nparams<-dim(trait.chains[[1]])[3]
    new.dimnames<-dimnames(trait.chains[[1]])
    new.dimnames[[3]]<-c(new.dimnames[[3]],
                         paste(colnames(fit$call$trait.data),'sig2',
                               c(tree$tip.label,ntips+1:tree$Nnode),sep='_'))
    trait.chains<-array(unlist(trait.chains),c(niter,nchains,2*nparams),new.dimnames)
    trait.chains<-aperm(trait.chains,c(1,3,2))
  }
  
  tmp.fit<-fit
  tmp.fit$chains<-trait.chains
  if(element!='chains'){
    if(element=='diagnostics'){
      tmp.dimnames<-dimnames(tmp.fit$param.diags)
      tmp.fit$param.diags<-array(NA,c(4,dim(trait.chains)[2],nchains),
                                 c(tmp.dimnames[1],dimnames(trait.chains)[2],tmp.dimnames[3]))
      tmp.fit$param.diags[2,,]<-apply(tmp.fit$chains,c(2,3),rstan::ess_bulk)
      tmp.fit$param.diags[3,,]<-apply(tmp.fit$chains,c(2,3),rstan::ess_tail)
      tmp.fit$param.diags[4,,]<-apply(tmp.fit$chains,c(2,3),rstan::Rhat)
    }else{
      if(element=='quantiles'&!is.null(fit$quantiles)){
        report.quantiles<-as.numeric(gsub('%','',dimnames(fit$quantiles)[[1]]))/100
      }
      tmp.fit[[element]]<-NULL
    }
  }

  if(is.null(select)){
    select<-dimnames(trait.chains)[[2]]
  }
  if(element=='quantiles'|element=='diagnostics'|element=='chains'&!is.null(select.extra)){
    select<-list(select,select.extra)
  }
  out<-do.call(paste('.int.',element,sep=''),list(fit=tmp.fit,select=select))
  if(simplify){
    out<-.simplify.element(out)
  }
  out
}